env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - make vendor

builds:
  - dir: sapcc/v2/valuetransformer
    binary: sapcc/v2/valuetransformer/ValueTransformer
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

  - dir: sapcc/v1/imageregistrytransformer
    binary: sapcc/v1/imageregistrytransformer/ImageRegistryTransformer
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    files:
      - LICENSE
      - sapcc/v2/valuetransformer/ValueTransformer
      - sapcc/v1/imageregistrytransformer/ImageRegistryTransformer
