env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - GOARCH=amd64

before:
  hooks:
    - make vendor

builds:
  - dir: sapcc/v2/valuetransformer
    binary: sapcc/v2/valuetransformer/ValueTransformer
    goos:
      - darwin
      - linux
    goarch:
      - amd64

archives:
  - format: tar.gz
    files:
      - LICENSE
      - sapcc/v1/valuetransformer/ValueTransformer
